apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xilo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xilo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xilo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xilo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xilo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zurw-tenant/rhtap-demo-app/hacbs-test-project-xilo@sha256:903480950066195cc16b6a285c156a844e837ae1c50c94d02b06b3a683613e6a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
